name: ADF-CopyActivity
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEVOPS_SECRET_CREDENTIALS }}
          enable-AzPSSession: true 

      - name: Deploy resources
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: rg-kdevops-prod
          dataFactoryName: kProdADF01
          armTemplateFile: ./kDevADF01/ARMTemplateForFactory.json
          armTemplateParametersFile: ./kDevADF01/ARMTemplateParametersForFactory.json
          # additionalParameters: 'key1=value key2=value keyN=value'
          skipAzModuleInstallation: true
