name: ADF-CopyActivity
on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: copy_activity
      run: Copy-Item "tests/a.txt" -Destination "tests/b.txt"
