name: ADF-Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    name: 'ADF code deloyment to the production'
    steps:
    - uses: actions/checkout@v3
    - name: Azure Login
      with: 
        creds: ${secrets.DEVOPS_SECRET_CREDENTIALS}
    - name: Deploy Azure DataFactory Code Template
      uses: Azure/arm-deploy@v1.0.6
      with:
        scope: 'resourcegroup'
        resourceGroupName: 'rg-kdevops-prod'
        template: ./kDevADF01/ARMTemplateForFactory.json
        deployment: Incremental
        parameters: factoryName=kTestADF001
