name: ADF-CopyActivity
on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: copyactivity/checkout@develop
    - name: copy_activity
      uses: TeamKagoolLtd/azuredatafactory-gitbuhpublic@develop
      with:
        source: "tests/a.txt"
        target: "test/a.txt"
